# -*- coding: utf-8 -*-
"""
/***************************************************************************
 CreateCustomProjection
                                 A QGIS plugin
 This plugin adds the Coordinate Reference System of a layer to Custom Projection List.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2021-05-26
        copyright            : (C) 2021 by Murat Çalışkan
        email                : caliskan.murat.20@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load CreateCustomProjection class from file CreateCustomProjection.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .create_custom_projection import CreateCustomProjection
    return CreateCustomProjection(iface)
